// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartScreen
{
    internal sealed partial class Vsix
    {
        public const string Id = "StartScreen.2d76ac3d-7ff2-47e1-82d8-e507cf765bbe";
        public const string Name = "Start Screen";
        public const string Description = @"A modern start screen for Visual Studio with MRU, developer news, and quick actions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "news, start";
        public const bool IsPreview = false;
    }
}
